version: '3.7'

services:

  seismic-app:
    container_name: seismic-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
